/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BankSol } from "./BankSol";
export * as factories from "./factories";
export { BankSol__factory } from "./factories/BankSol__factory";
